/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package FinalProject;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        registrarse();
        menu();
    }
    
    public static void registrarse() {
        boolean valid = false;
        
        do {
            System.out.println("Sign up");
            System.out.println("1. User");
            System.out.println("2. Administrator");
            
            Scanner input = new Scanner(System.in);
            
            System.out.print("Option: ");
            String option = input.nextLine();

            if ("1".equals(option)) {
                Usser usser1 = new Usser ("", "", "");
                usser1.getName();
                usser1.getUserName();
                usser1.getPassword();
            } else if ("2".equals(option)) {
                Admin admin1 = new Admin ("", "", "", "");
                admin1.getName();
                admin1.getUserName();
                admin1.getPassword();
                admin1.getCodeAdmin();
            } else {
                System.out.println("That is not an option");
                valid = true;
            }
        } while (valid);
    }
    
    public static void menu() {
        int option;
        // String answer = "";
        
        // This will have changes, in orden to be cycle
        // It only to prove
        Movie movie1 = new Movie("Spidermann", "Acción" , "Vida de un Superheroe", "Español", "Sam Raimi", "General", "2 hrs", "2004");
        Movie movie2 = new Movie("Spidermann 2", "Acción" , "Vida de un Superheroe", "Español", "Sam Raimi", "General", "2:30 hrs", "2006");
        Movie movie3 = new Movie("Spidermann 3", "Acción" , "Vida de un Superheroe", "Español", "Sam Raimi", "General", "2 hrs", "2008");
        
        Billboard billboard1 = new Billboard("");
        billboard1.addMovie(movie1);
        billboard1.addMovie(movie2);
        billboard1.addMovie(movie3);
        
        do {
            System.out.println("To continue, choose an option");
            System.out.println("1. Billboard");
            System.out.println("2. Reservation");
            System.out.println("3. Challenges");
            System.out.println("4. Exit");

            Scanner input = new Scanner(System.in);
            System.out.print("Option: ");
            option = input.nextInt();
            
            while (option < 1 || option > 4) {
                System.out.println("That is not an option");
                System.out.println("");
                System.out.println("Choose an option again");
                System.out.println("1. Billboard");
                System.out.println("2. Reservation");
                System.out.println("3. Challenges");
                System.out.println("4. Exit");
                System.out.print("Option: ");
                option = input.nextInt();
            }    

            if (option == 1) {
                billboard1.getBillboardTitle();
                billboard1.showMovies();
            } else if (option == 2) {

            } else if (option == 3) {

            } else {
                System.out.println("Take Care!");
                break;
            } 
        } while (option >= 1 && option < 4);
    } 
}

