/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package FinalProject;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        register();
        // administratorMenu();
        //userMenu();
    }
    
    public static void register() {
        boolean valid = false;
        
        do {
            System.out.println("Sign up");
            System.out.println("1. User");
            System.out.println("2. Administrator");
            
            Scanner input = new Scanner(System.in);
            
            System.out.print("Option: ");
            String option = input.nextLine();

            if ("1".equals(option)) {
                Usser usser1 = new Usser ("", "", "");
                usser1.getName();
                usser1.getUserName();
                usser1.getPassword();
                System.out.println("");
                userMenu();
                break;
            } else if ("2".equals(option)) {
                Admin admin1 = new Admin ("", "", "", "");
                admin1.getName();
                admin1.getUserName();
                admin1.getPassword();
                admin1.getCodeAdmin();
                System.out.println("");
                administratorMenu();
                break;
            } else {
                System.out.println("");
                System.out.println("That is not an option");
                valid = true;
            }
        } while (valid);
    }
    
    public static void administratorMenu() {
        String opt;
        boolean active = false;
        boolean on = false;
        
        // This will have changes, in orden to be cycle
        // It only to prove
        
        Movie movie1 = new Movie("Spidermann", "Acción" , "Vida de un Superheroe", "Español", "Sam Raimi", "General", "2 hrs", "2004");
        Movie movie2 = new Movie("Spidermann 2", "Acción" , "Vida de un Superheroe", "Español", "Sam Raimi", "General", "2:30 hrs", "2006");
        Movie movie3 = new Movie("Spidermann 3", "Acción" , "Vida de un Superheroe", "Español", "Sam Raimi", "General", "2 hrs", "2008");
       
        Billboard billboard1 = new Billboard("");
        billboard1.addMovie(movie1);
        billboard1.addMovie(movie2);
        billboard1.addMovie(movie3);
        
        Gamificacion gam1= new Gamificacion();
        Rankins ra = new Rankins();
        
        do {
            System.out.println("To continue, choose an option");
            System.out.println("1. Billboard");
            System.out.println("2. Reservation");
            System.out.println("3. Challenges");
            System.out.println("4. Comments and Rankins");
            System.out.println("5. Exit");
            
            Scanner input = new Scanner(System.in);
            System.out.print("Option: ");
            opt = input.nextLine();
            System.out.println("");  

            if ("1".equals(opt)) {
                String ans;
                
                do {
                    System.out.println("Choose an option: ");
                    System.out.println("1. Watch movies in Billboard");
                    System.out.println("2. Numbers of movies in Billboard");
                    System.out.println("3. Add some movie");
                    System.out.println("4. Eliminate some movie");
                    System.out.println("5. Search a movie by position");
                    System.out.println("6. Exit");

                    Scanner in = new Scanner(System.in);
                    System.out.print("Option: ");
                    ans = in.nextLine();
                    System.out.println("");

                    if ("1".equals(ans)) {
                        billboard1.getBillboardTitle();
                        System.out.println("");
                        billboard1.showMovies();
                        // System.out.println("");
                        on = true;
                    } else if ("2".equals(ans)) {
                        billboard1.getNumberMovies();
                        System.out.println("");
                        on = true;
                    } else if ("3".equals(ans)) {
                        String box;
                        String boxTitle;
                        String boxGenre;
                        String boxSynopsis;
                        String boxLenguage;
                        String boxDirector;
                        String boxClasification;
                        String boxDuration;
                        String boxYear;
                        System.out.println("");
                        // box = in.nextLine();
                        
                        System.out.println("Enter the title of the movie");
                        boxTitle = in.nextLine();
                        System.out.println("Enter the genre of the movie");
                        boxGenre = in.nextLine();
                        System.out.println("Enter the synopsis of the movie");
                        boxSynopsis = in.nextLine();
                        System.out.println("Enter the lenguage of the movie");
                        boxLenguage = in.nextLine();
                        System.out.println("Enter the director of the movie");
                        boxDirector = in.nextLine();
                        System.out.println("Enter the clasification of the movie");
                        boxClasification = in.nextLine();
                        System.out.println("Enter the duration of the movie");
                        boxDuration = in.nextLine();
                        System.out.println("Enter the year of the movie");
                        boxYear = in.nextLine();
                        System.out.println("");
                        
                        Movie mov = new Movie(boxTitle, boxGenre, boxSynopsis, boxLenguage, boxDirector, boxClasification, boxDuration, boxYear);
                        billboard1.addMovie(mov);
                        on = true;
                    } else if ("4".equals(ans)) {
                        String boxTitle;

                        System.out.println("Enter the title of the movie you want to delete");
                        boxTitle = in.nextLine();
                        
                        billboard1.removeMovie(boxTitle);
                        System.out.println("");
                        on = true;
                    } else if ("5".equals(ans)) {
                        int pos = 0;
                        billboard1.getMovieTitle(pos);
                        on = true;
                    } else if ("6".equals(ans)) {
                        on = false;
                        administratorMenu();
                        break;
                    } else {
                        System.out.println("That is not an option \n");
                        on = true;
                    }
                } while (on);
            } else if ("2".equals(opt)) {
                Reservations reser = new Reservations("", "", "");
                reser.getUser();
                reser.getUserName();
                reser.getPassword();
                System.out.println("");
                reser.reservationMenu();
                active = true;
            } else if ("3".equals(opt)) {
                gam1.gamificacionMenu();
                active = true;
            } else if ("4".equals(opt)){
                boolean exit = false;
                
                do{
                    System.out.println("Choose an option: ");
                    System.out.println("1. Write your comment");
                    System.out.println("2. Rate a movie");
                    System.out.println("3. See all coments of a movie");
                    System.out.println("4. See all the rates of a movie");
                    System.out.println("5. Exit");
                    
                    Scanner i = new Scanner(System.in);
                    System.out.print("Option: ");
                    String op = i.nextLine();
                    System.out.print("");
                    
                    if ("1".equals(op)) {
                        try {
                        String comment;
                        String comment1;
                        String comment2;
                        String sum;
                        // comment = input.nextLine();
                        System.out.println("Enter the name of the movie you want to comment");
                        comment1 = input.nextLine();
                        System.out.println("Enter yout comment about the movie");
                        comment2 = input.nextLine();
                        
                        sum = comment1 + "\n" + comment2;
                        ra.writeComment(sum, billboard1.existMovie(comment1));
                        } catch(Exception e) {
                            System.out.println("Enter a valid value \n");
                        }
                        exit = true;
                    } else if ("2".equals(op)){ 
                        try { 
                        String comment1;
                        String number;
                        
                        System.out.println("Enter the name of the movie you want to comment");
                        comment1 = input.nextLine();
                        System.out.println("Enter the rank of the movie");
                        number = input.nextLine();
                        
                        int num = Integer.parseInt(number);
                        ra.addRank(num, billboard1.existMovie(comment1));
                        exit = true;
                        } catch (NumberFormatException e) {
                            System.out.println("Enter a valid value \n");
                        }
                    } else if ("3".equals(op)) {
                        ra.printComment();
                        exit = true;
                    } else if ("4".equals(op)) {
                        ra.printRankin();
                        exit = true;
                    } else if ("5".equals(op)) {
                        exit = false;
                        administratorMenu();
                        break;
                    } else {
                        System.out.println("Select a valid value \n");
                        exit = true;
                    }
                } while (exit);
                break;
            } else if ("5".equals(opt)) {
                active = false;
                System.out.println("Thanks for visit us!");
                break;
            } else {
                System.out.println("That is not an option \n");
                active = true;
            }
        } while (active);
    } 
    
    public static void userMenu() {
        String opt;
        boolean active = false;
        boolean on = false;
        
        // This will have changes, in orden to be cycle
        // It only to prove
        
        Movie movie1 = new Movie("Spidermann", "Acción" , "Vida de un Superheroe", "Español", "Sam Raimi", "General", "2 hrs", "2004");
        Movie movie2 = new Movie("Spidermann 2", "Acción" , "Vida de un Superheroe", "Español", "Sam Raimi", "General", "2:30 hrs", "2006");
        Movie movie3 = new Movie("Spidermann 3", "Acción" , "Vida de un Superheroe", "Español", "Sam Raimi", "General", "2 hrs", "2008");
       
        Billboard billboard1 = new Billboard("");
        billboard1.addMovie(movie1);
        billboard1.addMovie(movie2);
        billboard1.addMovie(movie3);
        
        Gamificacion gam1= new Gamificacion();
        Rankins ra = new Rankins();
        
        do {
            System.out.println("To continue, choose an option");
            System.out.println("1. Billboard");
            System.out.println("2. Reservation");
            System.out.println("3. Challenges");
            System.out.println("4. Comments and Rankins");
            System.out.println("5. Exit");
            
            Scanner input = new Scanner(System.in);
            System.out.print("Option: ");
            opt = input.nextLine();
            System.out.println("");  

            if ("1".equals(opt)) {
                String ans;
                
                do {
                    System.out.println("Choose an option: ");
                    System.out.println("1. Watch movies in Billboard");
                    System.out.println("2. Numbers of movies in Billboard");
                    System.out.println("3. Search a movie by position");
                    System.out.println("4. Exit");

                    Scanner in = new Scanner(System.in);
                    System.out.print("Option: ");
                    ans = in.nextLine();
                    System.out.println("");

                    if ("1".equals(ans)) {
                        billboard1.getBillboardTitle();
                        System.out.println("");
                        billboard1.showMovies();
                        // System.out.println("");
                        on = true;
                    } else if ("2".equals(ans)) {
                        billboard1.getNumberMovies();
                        System.out.println("");
                        on = true;
                    } else if ("3".equals(ans)) {
                        int pos = 0;
                        billboard1.getMovieTitle(pos);
                        on = true;
                    } else if ("4".equals(ans)) {
                        on = false;
                        userMenu();
                        break;
                    } else {
                        System.out.println("That is not an option \n");
                        on = true;
                    }
                } while (on);
            } else if ("2".equals(opt)) {
                Reservations reser = new Reservations("", "", "");
                reser.getUser();
                reser.getUserName();
                reser.getPassword();
                System.out.println("");
                reser.reservationMenu();
                active = true;
            } else if ("3".equals(opt)) {
                gam1.gamificacionMenu();
                active = true;
            } else if ("4".equals(opt)){
                boolean exit = false;
                
                do{
                    System.out.println("Choose an option: ");
                    System.out.println("1. Write your comment");
                    System.out.println("2. Rate a movie");
                    System.out.println("3. See all coments of a movie");
                    System.out.println("4. See all the rates of a movie");
                    System.out.println("5. Exit");
                    
                    Scanner i = new Scanner(System.in);
                    System.out.print("Option: ");
                    String op = i.nextLine();
                    System.out.print("");
                    
                    if ("1".equals(op)) {
                        try {
                        String comment;
                        String comment1;
                        String comment2;
                        String sum;
                        // comment = input.nextLine();
                        System.out.println("Enter the name of the movie you want to comment");
                        comment1 = input.nextLine();
                        System.out.println("Enter yout comment about the movie");
                        comment2 = input.nextLine();
                        
                        sum = comment1 + "\n" + comment2;
                        ra.writeComment(sum, billboard1.existMovie(comment1));
                        } catch(Exception e) {
                            System.out.println("Enter a valid value \n");
                        }
                        exit = true;
                    } else if ("2".equals(op)){ 
                        try { 
                        String comment1;
                        String number;
                        
                        System.out.println("Enter the name of the movie you want to comment");
                        comment1 = input.nextLine();
                        System.out.println("Enter the rank of the movie");
                        number = input.nextLine();
                        
                        int num = Integer.parseInt(number);
                        ra.addRank(num, billboard1.existMovie(comment1));
                        exit = true;
                        } catch (NumberFormatException e) {
                            System.out.println("Enter a valid value \n");
                        }
                    } else if ("3".equals(op)) {
                        ra.printComment();
                        exit = true;
                    } else if ("4".equals(op)) {
                        ra.printRankin();
                        exit = true;
                    } else if ("5".equals(op)) {
                        exit = false;
                        userMenu();
                        break;
                    } else {
                        System.out.println("Select a valid value");
                        exit = true;
                    }
                } while (exit);
                break;
            } else if ("5".equals(opt)) {
                active = false;
                System.out.println("Thanks for visit us!");
                break;
            } else {
                System.out.println("That is not an option \n");
                active = true;
            }
        } while (active);
    }
}

