/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package FinalProject;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        // registrarse();
        menu();
    }
    
    public static void registrarse() {
        boolean valid = false;
        
        do {
            System.out.println("Sign up");
            System.out.println("1. User");
            System.out.println("2. Administrator");
            
            Scanner input = new Scanner(System.in);
            
            System.out.print("Option: ");
            String option = input.nextLine();

            if ("1".equals(option)) {
                Usser usser1 = new Usser ("", "", "");
                usser1.getName();
                usser1.getUserName();
                usser1.getPassword();
                break;
            } else if ("2".equals(option)) {
                Admin admin1 = new Admin ("", "", "", "");
                admin1.getName();
                admin1.getUserName();
                admin1.getPassword();
                admin1.getCodeAdmin();
                break;
            } else {
                System.out.println("That is not an option");
                valid = true;
            }
        } while (valid);
    }
    
    public static void menu() {
        int option;
        boolean active = false;
        
        // This will have changes, in orden to be cycle
        // It only to prove
        // Movie movie1 = new Movie("Spidermann", "Acción" , "Vida de un Superheroe", "Español", "Sam Raimi", "General", "2 hrs", "2004");
        // Movie movie2 = new Movie("Spidermann 2", "Acción" , "Vida de un Superheroe", "Español", "Sam Raimi", "General", "2:30 hrs", "2006");
        // Movie movie3 = new Movie("Spidermann 3", "Acción" , "Vida de un Superheroe", "Español", "Sam Raimi", "General", "2 hrs", "2008");
        
        // Billboard billboard1 = new Billboard("");
        // billboard1.addMovie(movie1);
        // billboard1.addMovie(movie2);
        // billboard1.addMovie(movie3);
        
        Movie movie1 = new Movie("Spidermann", "Acción" , "Vida de un Superheroe", "Español", "Sam Raimi", "General", "2 hrs", "2004");
        Movie movie2 = new Movie("Spidermann 2", "Acción" , "Vida de un Superheroe", "Español", "Sam Raimi", "General", "2:30 hrs", "2006");
        Movie movie3 = new Movie("Spidermann 3", "Acción" , "Vida de un Superheroe", "Español", "Sam Raimi", "General", "2 hrs", "2008");

        Billboard billboard1 = new Billboard("");
        billboard1.addMovie(movie1);
        billboard1.addMovie(movie2);
        billboard1.addMovie(movie3);
        
        Gamificacion gam1= new Gamificacion();
        Rankins ra = new Rankins();
        
        do {
            System.out.println("To continue, choose an option");
            System.out.println("1. Billboard");
            System.out.println("2. Reservation");
            System.out.println("3. Challenges");
            System.out.println("4. Coments and rankins");
            System.out.println("5. Exit");

            Scanner input = new Scanner(System.in);
            System.out.print("Option: ");
            option = input.nextInt();
            
            while (option < 1 || option > 4) {
                System.out.println("That is not an option");
                System.out.println("");
                System.out.println("Choose an option again");
                System.out.println("1. Billboard");
                System.out.println("2. Reservation");
                System.out.println("3. Challenges");
                System.out.println("4. Coments and rankins");
                System.out.println("5. Exit");
                System.out.print("Option: ");
                option = input.nextInt();
            }    

            if (option == 1) {
                int ans;
                
                do {
                    System.out.println("Choose an option: ");
                    System.out.println("1. Watch movies in Billboard");
                    System.out.println("2. Numbers of movies in Billboard");
                    System.out.println("3. Add some movie");
                    System.out.println("4. Search a movie by position");
                    System.out.println("5. Search a movie by criteria");
                    System.out.println("6. Exit");

                    Scanner in = new Scanner(System.in);
                    System.out.print("Option: ");
                    ans = in.nextInt();

                    while (ans < 1 || ans > 5) {
                        System.out.println("That is not an option");
                        System.out.println("");
                        System.out.println("Choose an option: ");
                        System.out.println("1. Watch movies in Billboard");
                        System.out.println("2. Numbers of movies in Billboard");
                        System.out.println("3. Add some movie");
                        System.out.println("4. Search a movie by position");
                        System.out.println("5. Search a movie by criteria");
                        System.out.println("6. Exit");
                        System.out.print("Option: ");
                        ans = in.nextInt();
                    }

                    if (ans == 1) {
                        billboard1.getBillboardTitle();
                        billboard1.showMovies();
                    } else if (ans == 2) {
                        billboard1.getNumberMovies();
                    } else if (ans == 3) {
                        String box;
                        String boxtitle;
                        String boxgenre;
                        String boxsynopsis;
                        String boxlenguage;
                        String boxdirector;
                        String boxclasification;
                        String boxduration;
                        String boxyear;
                        System.out.println("");
                        box = in.nextLine();
                        System.out.println("Enter the title of the movie");
                        boxtitle = in.nextLine();
                        System.out.println("Enter the genre of the movie");
                        boxgenre = in.nextLine();
                        System.out.println("Enter the synopsis of the movie");
                        boxsynopsis = in.nextLine();
                        System.out.println("Enter the lenguage of the movie");
                        boxlenguage = in.nextLine();
                        System.out.println("Enter the director of the movie");
                        boxdirector = in.nextLine();
                        System.out.println("Enter the clasification of the movie");
                        boxclasification = in.nextLine();
                        System.out.println("Enter the duration of the movie");
                        boxduration = in.nextLine();
                        System.out.println("Enter the year of the movie");
                        boxyear = in.nextLine();
                        Movie mov = new Movie(boxtitle,boxgenre,boxsynopsis,boxlenguage,boxdirector,boxclasification,boxduration,boxyear);
                        billboard1.addMovie(mov);
                    } else if (ans == 4) {
                        billboard1.eliminateMovie(movie3);
                    } else if (ans == 5) {
                        String box;
                        String criteria;
                        String parameter;
                        box = in.nextLine();
                        System.out.println("Enter the criteria of the movie");
                        criteria = in.nextLine();
                        System.out.println("Enter the parameter of the movie");
                        parameter = in.nextLine();
                        billboard1.searchMovieCriteria(criteria, parameter);
                    } else {
                        System.out.println("Take Care!");
                        break;
                    }
                } while (ans >= 1 && ans < 5);
                
            } else if (option == 2) {
                Reservations reser = new Reservations("", "", "");
                reser.reservationMenu();
                menu();
                // reser.reserve();
            } else if (option == 3) {
                gam1.gamificacionMenu();
            } else if (option == 4) {
                boolean exit = false;
                do{
                    System.out.println("Choose an option: ");
                    System.out.println("1. write your comment");
                    System.out.println("2. rate a movie");
                    System.out.println("3. see all coments of a movie");
                    System.out.println("4. see all the rates of a movie");
                    System.out.println("5. exit");
                    Scanner i = new Scanner(System.in);
                    String op = i.nextLine();
                    if(op.equals("1")){
                        try{
                        String comment;
                        String comment1;
                        String comment2;
                        String sum;
                        comment = input.nextLine();
                        System.out.println("Enter the name of the movie you want to comment");
                        comment1 = input.nextLine();
                        System.out.println("Enter yout comment about the movie");
                        comment2 = input.nextLine();
                        sum = comment1 + "\n" + comment2;
                        ra.writeComment(sum,billboard1.existMovie(comment1));
                        exit = true;
                        }catch(Exception e){
                            System.out.println("Enter a valid value");
                        }
                    }else{ 
                        if(op.equals("2")){
                           try{ 
                            String comment1;
                            String number;
                            System.out.println("Enter the name of the movie you want to comment");
                            comment1 = input.nextLine();
                            System.out.println("Enter the rank of the movie");
                            number = input.nextLine();
                            int num = Integer.parseInt(number);
                            ra.addRank(num ,billboard1.existMovie(comment1));
                            exit = true;
                           }catch(Exception e){
                               System.out.println("Enter a valid value");
                           }
                        }else{
                            if(op.equals("3")){
                                ra.printComment();
                                exit = true;
                            }else{
                                if(op.equals("4")){
                                    ra.printRankin();
                                    exit = true;

                                }else{
                                    if(op.equals("5")){
                                        exit = false;
                                    }else{
                                        System.out.println("select a valid value");
                                        exit = true;
                                    }
                                }
                            }
                        }    
                    }
                    }while(exit);
            
            } else {
                System.out.println("Take Care!");
                active = false;
            } 
        } while (active);
    } 
}

